### ISSUE TITLE
Problem mit Community Netzen

### ISSUE THREAD

**Issue by DaCHRIS** [freifunk/icvpn-meta#103]
Moin moin,

ich finde das eigentlich nicht so richtig prall, dass die Zuteilung IP-Netz / ASN nun hier über das Repo erfolgen soll, aber man kann sich dem nicht entziehen. 

Als ich nun unsere Community Netze anlegen wollte, (zu denen mir gesagt wurde ich müsste diese einzeln anlegen, da jede Community eine eigene ASN hat und mehrere ASN pro File nicht zulässig sind) rannte die Prüfung direkt auf nen Hammer, da es anscheinend ebenfalls nicht zulässig ist mehrere ASN in unterschiedlichen Files über das selbe Gateway zu routen. 

Was nun? 

Sieh PR #101  #102

**Comment by mweinelt** [comment]
Ja, die Struktur lässt das im Moment nicht zu. Es gibt da noch ein paar offene Fragen, bevor wir eine Lösung dazu finden können.

Zunächst: Mit parsebaren Daten (hier: yaml) haben wir eine bessere Handhabe über alle Allokationen, quasi wie bei einer Registry. Es ist besser nachzuvollziehen, wer wann welche Änderungen an der Allokation vorgenommen hat, oder wer der Ansprechpartner dafür ist. Wir können zudem aus den aufbereiteten Daten allerlei Konfigurationen generieren.
Zugegebenermaßen erhöht das die Einstiegshürde, allerdings sollte git bzw diff/patch keinen Freifunk-Administrator überfordern.

Können BGP-Daemons (vorrangig bird und quagga) denn überhaupt mit so einer Konfiguration (mehrere ASN je Peer) umgehen? Wie sähen Beispielkonfigurationen dafür aus?

Wir erkennen auch die Schwächen der bisherigen Struktur, werden die aber sicherlich am WCW ansprechen und Lösungsansätze diskutieren. Insbesondere sollten meiner Meinung nach einzelne Objekte referenzierbar sein.

**Comment by DaCHRIS** [comment]
Klar, Multi-AS ist kein Problem. 

In unserem Fall ist es aber anders. 

Die ASN der Communities hängen hinter dem Hauptnetz. 

Also AS65079 ist directly connected, die bspw. AS65405 ist über den Pfad 65079, 65405 erreichbar. 

Unsere Topologie ist mittlerweile komplett BGP geroutet, um unser Netz nicht noch weiter zu vergrößern. 

Im Grunde genommen könnte ich auch einfach erstmal nur alle IP-Netze in das Ruhrgebiets-File reinkippen, denn AS65079 weiß ja wo jedes Netz hin muss, dann sind nur die ASN nicht bekannt. 

Soll ich das erstmal so machen?

**Comment by leeps** [comment]
Lass den Abschnitt für BGP einfach raus aus der Config, wenn Ihr da eh nur intern peert?
