### ISSUE TITLE
Are these AS numbers valid?

### ISSUE THREAD

**Issue by indigo423** [freifunk/icvpn-meta#116]
There are AS numbers larger then 16 bit registered:

 - luebeck:asn: 201173
 - rhein-neckar:asn: 76118

**Comment by mweinelt** [comment]
Yes, they are. The first one is global, the second...is up to debate.

Check out: https://tools.ietf.org/html/rfc4893

**Comment by wusel42** [comment]
@indigo423 Yepp, see e. g. https://www.ripe.net/manage-ips-and-asns/resource-management/faq/faq-asn32

**Comment by indigo423** [comment]
thx for explanation.
