### ISSUE TITLE
duplicate ipv4 subnet 10.31/16: Berlin vs. Hameln

### ISSUE THREAD

**Issue by FreifunkUFO** [freifunk/icvpn-meta#224]
10.31/16 ist eigentlich für Berlin reserviert.
@mmunz hat das jetzt für Hameln nochmal registriert:

https://github.com/openwrt/luci/commit/69ecfff002452c8ac220c4fe83156c4dfa985fa0

**Comment by mweinelt** [comment]
@mmunz Wenn die Community jemals ICVPN routen möchte, dann bietet sich jetzt ein Wechsel und eine Allokation im icvpn-meta an.
