### ISSUE TITLE
Reservierung für private Netze

### ISSUE THREAD

**Issue by engpire** [freifunk/icvpn-meta#365]
Es wäre schön, wenn nicht das ganze 10.0.0.0/8er Netz für "öffentliche" Freifunk-IPs genutzt würde, sondern wenn ein kleiner Teilbereich (z.B. /12) für private LAN genutzt werden könnte ohne einen Adresskonflikt zu provozieren.

**Comment by wusel42** [comment]
Warum sind die anderen RFC1918-Bereiche dafür nicht ausreichend? Ganz abgesehen davon, daß die Entscheidung pro 10/8 schon ein paar Jahre zurückliegt.

**Comment by engpire** [comment]
Die Frage ist nicht, ob die Bereiche ausreichend sind oder nicht. Nach dieser Argumentation müsste neben 172.16.0.0/12 auch kein 192.168.0.0/16 existieren. Maßgeblich ist für mich die Frage ob ich als Freifunker die Möglichkeit habe,  auch den dritten in der RFC definierten Adressbereich zu nutzen.

An einer jahrelang zurückliegenden Entscheidung wäre interessant, warum sie so gefällt wurde, nicht dass sie gefällt wurde.

**Comment by mweinelt** [comment]
Das war auch schon vor meiner Zeit, und ich sehe auch den Bedarf für einen gemeinsamen Testbereich, nicht jeder seinen eigenen. Es kommt ja tatsächlich nur darauf an, was nachher announced wird.

**Comment by wusel42** [comment]
Wieso man einerseits am ICVPN teilnehmen will (sonst stellt sich das Problem nicht), ohne Teil einer Community zu sein (jene hätte ja konfliktfreien Adressraum) und das zwingend mit 10er Adressen, obwohl der 172er-und 192er-Bereich aus 1918 zur Verfügung steht, erschließt sich mir nach wie vor nicht. Und die Begründung, daß es schön wäre, halte ich nicht für ausreichend, irgendeine Aktion auszulösen.

Kurzum: ohne nachvollziehbaren use case, warum man ein /12 aus 10/8 jetzt wofür loseisen sollte und wo und wieso das für FF/ICVPN vorteilhaft wäre, sollte dies geschlossen werden.

**Comment by engpire** [comment]
"wäre schön" ist ein genau so wenig tragfähiges Argument wie "war schon immer so". Einen praktischen Nutzen kann es für das VPN nicht geben da dieser Bereich ja gerade außerhalb läge. Genau so wenig sind die übrigen privaten Adressbereiche von "Nutzen" für das Internet - zumindest wenn man die Netze nur in ihrer immanenten Struktur betrachtet.
Von Vorteil ist jedoch der Lerneffekt beim Basteln mit den Netzen und die Möglichkeit, einen Playground zu haben.

**Comment by wusel42** [comment]
Ich fasse also zusammen: für das ICVPN und die Communities bringt es nichts, wäre für diese auch nicht »schön«, da Mehraufwand/weniger verfügbare Adressen.

Ohne Ziel der Verbindung mit dem ICVPN ist 10.0.0.0/8 jedoch nach wie vor beliebig nutzbar, eine Reservierung von Spieladressen innerhalb des ICVPN bzw. des »Freifunk-/8« ist schon deshalb überflüssig.

Es steht z. B. mit 172.16.0.0/12 ausreichend Addressraum für einen »Playground« außerhalb des ICVPN-/Freifunk-Adressbereichs zur Verfügung, mit 100.64.0.0/10 ein noch größerer Bereich, bei dem Kollisionen mit 10.0.0.0/8 ausgeschlossen sind.

Wer private Netze, z. B. Freifunk-Netze, mit anderen privaten Netzen verbinden will, wird einen Tod sterben müssen; im Falle Freifunk also entweder 10/8 komplett auf der Freifunk-Seite belassen oder die eigenen 10er Subnetze priorisiert routen -- und Verbindung in die eine oder andere Richtung einbüßen. (Naja, es gibt auch 1:1 NAT, wenn man denn unbedingt will …) Oder lokal renumbern.

Und just for the records: Es gibt derzeit noch 4 /14er Bereiche, größere zusammenhängende Blöcke sind aktuell lt. "findfree" nicht mehr verfügbar.
