### ISSUE TITLE
How do I find a free ip for a new community?

### ISSUE THREAD

**Issue by rubo77** [freifunk/icvpn-meta#433]
Is there an easy way to extract all given IPs from this repository?

I would just pick any new IP and search for this IP in this repositroy and hope it is free? but that seems a bit rude

for example 10.88 seems to be free, but it seems to be taken by Frankfurt Großenried aloready???

**Comment by Ranlvor** [comment]
We have a python-skript for that.
```
git clone https://github.com/freifunk/icvpn-scripts.git # get the icvpn-tooling
git clone https://github.com/freifunk/icvpn-meta.git # get the information about used nets
python3 icvpn-scripts/findfree -p 23 # get suggestions for starting with a /23
```

If you just want some /20s you do not even have to do that, there is a hosted solution: http://netblocks.icvpn.starletp9.de/findfree
