### ISSUE TITLE
Unexpected ICVPN BGP connections after "Grossreinemachen"

### ISSUE THREAD

**Issue by ecsv** [freifunk/icvpn-meta#511]
Just noticed that one of the FFV servers (vogtland3) had a full HDD and the reason for that was a rather big daemon.log. The "culprit" was bird which logged a lot of connection requests from unknown peers. Unfortunately, the log on this server cannot be used anymore - but I've checked on vogtland1 and vogtland4 for the same error messages via

    sudo grep 'Unexpected connect from unknown address' /var/log/daemon.log|sed -e 's/.*Unexpected connect from unknown address//' -e 's/port.*$//'|sort|uniq -c |sort -n

I found following IPs:

* misconfigured servers?
  - tuttlingen @kpanic23
    + `10.119.0.8`
  - ulm @kerlerm
    + `10.33.80.1`
  - franken @RedDog99
    + `10.83.252.14`
    + `fec0::a:cf:0:17` (why was it removed in 3c89032de1bf?)
* unknown and most likely unrelated to icvpn
  - `198.20.87.98`
  - `45.55.21.184`
  - `71.6.135.131`
  - `80.82.77.139`
  - `80.82.77.33`
* entries which were disabled during the "Grossreinemachen" #507 @kpanic23
  - hamburg @7adietri
    + `10.207.0.61`
    + `fec0::a:cf:0:3d`
  - nord @rubo77 @Tarnatos
    + `fec0::a:cf:b:c`

The first two points are not actually a problem of icvpn-meta. But the last point is the interesting part. Should these be re-added or should there certificate be removed from the icvpn tinc keys repository? And should `fec0::a:cf:0:17` be re-added for franken?

**Comment by ecsv** [comment]
Just had a look at https://github.com/freifunk/icvpn/pull/213 - but this pull request doesn't remove hamburg01 and nordgw0. And these are the servers which tried to connect to vogtland1 and vogtland4

**Comment by RedDog99** [comment]
Hi

Am 8. September 2017 09:26:49 MESZ schrieb Sven Eckelmann <notifications@github.com>:
>Just noticed that one of the FFV servers (vogtland3) had a full HDD and
>the reason for that was a rather big daemon.log. The "culprit" was bird
>which logged a lot of connection requests from unknown peers.
>Unfortunately, the log on this server cannot be used anymore - but I've
>checked on vogtland1 and vogtland4 for the same error messages via
>
>sudo grep 'Unexpected connect from unknown address'
>/var/log/daemon.log|sed -e 's/.*Unexpected connect from unknown
>address//' -e 's/port.*$//'|sort|uniq -c |sort -n
>
>I found following IPs:
>
>* misconfigured servers?
>  - tuttlingen @kpanic23
>    + `10.119.0.8`
>  - ulm @kerlerm
>    + `10.33.80.1`
>  - franken @RedDog99
>    + `10.83.252.14`
Opsi. Thanks for watching out.

I looked up this IP and it belongs to one of mayosemmels (in CC) machines.

@mayosemmel please take a look. And please enter this IP to our DNS service. ;)

>    + `fec0::a:cf:0:17` (why was it removed in 3c89032de1bf?)

Because we don't serve Ipv6 at the moment. We are working on it, but it takes times. :(

>* unknown and most likely unrelated to icvpn
>  - `198.20.87.98`
>  - `45.55.21.184`
>  - `71.6.135.131`
>  - `80.82.77.139`
>  - `80.82.77.33`
>* entries which were disabled during the "Grossreinemachen" #507
>@kpanic23
>  - hamburg @7adietri
>    + `10.207.0.61`
>    + `fec0::a:cf:0:3d`
>  - nord @rubo77 @Tarnatos
>    + `fec0::a:cf:b:c`
>
>The first two points are not actually a problem of icvpn-meta. But the
>last point is the interesting part. Should these be re-added or should
>there certificate be removed from the icvpn tinc keys repository? And
>should `fec0::a:cf:0:17` be re-added for franken?

For Franken: no, thanks. :)

Kind regards
Tim

**Comment by RedDog99** [comment]
Hi there,

I will look at it tonight.
Thanks for the information.

Best regards
Jan

Am 8. September 2017 10:26:58 MESZ schrieb Tim Niemeyer <tim@tn-x.org>:
>Hi
>
>Am 8. September 2017 09:26:49 MESZ schrieb Sven Eckelmann
><notifications@github.com>:
>>Just noticed that one of the FFV servers (vogtland3) had a full HDD
>and
>>the reason for that was a rather big daemon.log. The "culprit" was
>bird
>>which logged a lot of connection requests from unknown peers.
>>Unfortunately, the log on this server cannot be used anymore - but
>I've
>>checked on vogtland1 and vogtland4 for the same error messages via
>>
>>sudo grep 'Unexpected connect from unknown address'
>>/var/log/daemon.log|sed -e 's/.*Unexpected connect from unknown
>>address//' -e 's/port.*$//'|sort|uniq -c |sort -n
>>
>>I found following IPs:
>>
>>* misconfigured servers?
>>  - tuttlingen @kpanic23
>>    + `10.119.0.8`
>>  - ulm @kerlerm
>>    + `10.33.80.1`
>>  - franken @RedDog99
>>    + `10.83.252.14`
>Opsi. Thanks for watching out.
>
>I looked up this IP and it belongs to one of mayosemmels (in CC)
>machines.
>
>@mayosemmel please take a look. And please enter this IP to our DNS
>service. ;)
>
>>    + `fec0::a:cf:0:17` (why was it removed in 3c89032de1bf?)
>
>Because we don't serve Ipv6 at the moment. We are working on it, but it
>takes times. :(
>
>>* unknown and most likely unrelated to icvpn
>>  - `198.20.87.98`
>>  - `45.55.21.184`
>>  - `71.6.135.131`
>>  - `80.82.77.139`
>>  - `80.82.77.33`
>>* entries which were disabled during the "Grossreinemachen" #507
>>@kpanic23
>>  - hamburg @7adietri
>>    + `10.207.0.61`
>>    + `fec0::a:cf:0:3d`
>>  - nord @rubo77 @Tarnatos
>>    + `fec0::a:cf:b:c`
>>
>>The first two points are not actually a problem of icvpn-meta. But the
>>last point is the interesting part. Should these be re-added or should
>>there certificate be removed from the icvpn tinc keys repository? And
>>should `fec0::a:cf:0:17` be re-added for franken?
>
>For Franken: no, thanks. :)
>
>Kind regards
>Tim

**Comment by mweinelt** [comment]
@ecsv This is related to how peer builds its network graph. Every peer may introduce other peers it knows, so we can't really get rid of peers unless everyone upgrades.

There are some options I meant to take a look at, namely TunnelServer and StrictSubnets.

**Comment by 7adietri** [comment]
I'm trying to find out where this is coming from for Hamburg.

**Comment by kpanic23** [comment]
Well, it seems like hamburg1 bgp had been down for quite a long time and came back a week after getting removed during Großreinemachen... So I think the solution would be to remove the comment in hamburg meta file for this host, since it seems to be working again. But I guess that should be up to the hamburgerians...

**Comment by Tarnatos** [comment]
I've disabled tinc on vpn0 now. Maybe we'll check it later.

**Comment by ecsv** [comment]
The logs of vogtland(1,3,4) from today contained following "offenders" with ~75k connection requests in the last 10 hours:

* Franken: @RedDog99 @mayosemmel
  -  `fec0::a:cf:0:17`
* Hamburg: @7adietri @ohrensessel
  - `10.207.0.61`
  - `fec0::a:cf:0:3d`

**Comment by ohrensessel** [comment]
Hi,

hamburg1 is back since around mid of August. Before, tincd kept crashing and our motivation was low to fix icvpn as we nevertheless have public, unfiltered IPv6 in our mesh. tinc should now automatically be restarted in case it crashed. Additionally, all icvpn peers are now passive on our side to avoid unnecessary connection attempts from our side. Sorry for that, @ecsv.
I was not aware of Großreinemachen, otherwise I would have voted for keeping hamburg1 for the moment.

Hamburg2 will come back in a week or so.

Kind regards,
Leo

**Comment by RedDog99** [comment]
Hi Sven

Am Samstag, den 09.09.2017, 03:19 -0700 schrieb Sven Eckelmann:
> The logs of vogtland(1,3,4) from today contained following
> "offenders" with ~75k connection requests in the last 10 hours:
> Franken: @RedDog99 @mayosemmel
> fec0::a:cf:0:17

Ah damit. :/

You are right. This peering IP is configured. Also there are no IPv6
networks, this host has an IPv6 peering IP.

I will fix this, sorry for the noise.

Tim

**Comment by ecsv** [comment]
Looks like the relevant messages now disappeared from my logs after the mentioned communities fixed their icvpn-meta entries or disabled icvpn. @mweinelt Would you agree that this ticket can be closed now?

**Comment by ecsv** [comment]
I am assuming that this is a "yes, can be closed".

@RedDog99 I see from time to time that 10.83.252.14 is trying to connect. Maybe setting it to non-multihop BGP (aka direct) sessions could work around this problem.

**Comment by RedDog99** [comment]
Hi Sven

Am Sonntag, den 17.09.2017, 01:36 -0700 schrieb Sven Eckelmann:
> I am assuming that this is a "yes, can be closed".
> @RedDog99 I see from time to time that 10.83.252.14 is trying to 
I don't see what's wrong about a connection try.

But anyway this IP is in the responsibility of mayosemmel (CC).

Kind regards
Tim
