### ISSUE TITLE
ennepe-ruhr-kreis: Missing delegates in ruhrgebiet

### ISSUE THREAD

**Issue by ecsv** [freifunk/icvpn-meta#518]
Following networks are announced by ennepe-ruhr-kreis even when they were not delegated by ruhrgebiet to it.

 * 10.20.128.0/19 ASN 65400
 * 10.20.160.0/19 ASN 65400
 * 10.20.192.0/19 ASN 65400
 * 10.20.32.0/19 ASN 65400
 * 10.20.64.0/19 ASN 65400
 * 10.20.96.0/19 ASN 65400

@fragstone, @DaCHRIS

**Comment by fragstone** [comment]
corrected in the meta file

**Comment by mweinelt** [comment]
fixed in #523
