### ISSUE TITLE
bielefeld: Incorrect ASN for announced networks

### ISSUE THREAD

**Issue by ecsv** [freifunk/icvpn-meta#520]
The networks are set in ICVPN to 65529. But instead 4242420022 is used for them this currently breaks ROA checks on other BGP peers. icvpn's mkroa uses the data from icvpn-meta to generate this table. The icvpn-meta information must therefore be in sync with ASN used for the announcements.

 * 10.26.48.0/20 ASN 4242420022
 * 10.26.64.0/18 ASN 4242420022
 * fdef:17a0:ffb1:ffff::/64 ASN 4242420022

Maybe this could be used as an example for find a workaround for other communities like 

 * 10.31.0.0/24 ASN 4242421279
 * fda1:384a:74de::/48 ASN 4242423214

**Comment by mweinelt** [comment]
At least `10.31.0.0/24` is a colliding space that some dn42 user announces, not freifunk related at all. So ROA is right about blocking that.

**Comment by ecsv** [comment]
Seems that the bielefeld stuff was merged.
