### ISSUE TITLE
neonetwork: new nameserver breaks mkdns

### ISSUE THREAD

**Issue by belzebub40k** [freifunk/icvpn-meta#609]
The last commit https://github.com/freifunk/icvpn-meta/commit/763c74e4f5f6f3d10637b8e056067c11efdfc5f6 for neonetwork breaks the mkdns script from icvpn-scripts.

```
Traceback (most recent call last):
  File "/home/admin/clones/icvpn-scripts/mkdns", line 190, in <module>
    [filters[options.filter]] if options.filter else [])
  File "/home/admin/clones/icvpn-scripts/mkdns", line 138, in create_config
    formatter.add_data(domains, servers)
  File "/home/admin/clones/icvpn-scripts/mkdns", line 28, in add_data
    """ % (domain, "; ".join(servers))).lstrip())
TypeError: sequence item 1: expected str instance, dict found

```

It looks like the script does not like IPv6 addresses with `::` at the end.
Changing _fd10:127:ffff:53::_ to _fd10:127:ffff:53::**0**_ seems to fix it.

**Comment by mweinelt** [comment]
Fixed in https://github.com/freifunk/icvpn-meta/commit/ae6bf8a6501dba2906a384f34ed6f1a3272e39a4
