### ISSUE TITLE
I had a pending comment.

### ISSUE THREAD

**Issue by Angelstjes** [freifunk/icvpn-meta#625]
I had a pending comment.

_Originally posted by @foolip in https://github.com/mdn/browser-compat-data/pull/17096#pullrequestreview-1049433047_

**Comment by Angelstjes** [comment]
Sombody  jus my name i know its my   wife my and the3 childeren love here a lot hope that gob can do somting for us and  White 3 Lively Kids and  a happy papAits ead to see how the give for wife drugs to ged honny and later make amateur movies vrom her her dochter is 10 son 4 Angel deprinces2 help

**Comment by wusel42** [comment]
Spam via issues?
