### ISSUE TITLE
Enforce hexadecimal representation of last IPv4 octet in last IPv6 hextet

### ISSUE THREAD

**Issue by mweinelt** [freifunk/icvpn-meta#70]
Where are we going with this? The check currently breaks only because of this, so do we want to enforce this at some point or loosen the check?

Opinions welcome!

**Comment by tcatm** [comment]
We could check whether the IPs are reachable in icvpn. If they are not, determine whether the community still exists and eventually remove the entries.

If the community is still active we should explain the situation to their administrators and ask them to resolve this.

In the meantime it may be possible report only errors in files changed by a pull requests and treat older errors as warnings.

**Comment by mweinelt** [comment]
Check temporarily disabled in https://github.com/freifunk/icvpn-scripts/commit/47a8112dd38e832a048c116621f22698d348d870

This check makes reviewing more tedious, becuase of a permanent fail state of the test suite.
This test case should return as a warning though and should still be looked at when merging pull requests.
